{% set version = "32.0.0" %}

package:
  name: pip-requirements-parser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pip-requirements-parser/pip-requirements-parser-{{ version }}.tar.gz
  sha256: 5159b8a9485a5a0d0254a29c9bd8b8ce66db2eb9a1a0244c64dfce43f7f2ac90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=4
  run:
    - packaging <22.0.0
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - pip_requirements_parser
  commands:
    - pip check
    {% set skips = '-k "not skeleton_codestyle"' %}
    {% set cov = 89 %}
    {% set skips = '-k "not (to_dict or dumps_unparse or unexisting_path)"' %}  # [win]
    {% set cov = 84 %}  # [win]
    - cd tests && pytest -vv --cov pip_requirements_parser --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under {{ cov }} {{ skips }}
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/nexB/pip-requirements-parser
  summary: pip requirements parser - a mostly correct pip requirements parsing library because it uses pip's own code.
  license: MIT
  license_file:
    - LICENSE
    # this is the pip license
    - mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
